columnSuffix: eewflaea
contentColumnType: text
fieldGroup: 6ea547fb-7732-477d-a633-073ad70b7233 # Home Banner 1
handle: banner1Title
instructions: 'Two line Display Intro of Tab 1'
name: Banner-1-Title
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: 'Here we have a two line display intro. (Tab 1)'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
