columnSuffix: iluthuab
contentColumnType: text
fieldGroup: 7a277a0a-ee6c-4522-b7fa-8e3021062db2 # Home Banner 2
handle: banner2Title
instructions: 'Two line Display Intro of Tab 2'
name: Banner-2-Title
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: 'Two line Display Intro of Tab 2'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
