columnSuffix: tqnfzxbc
contentColumnType: text
fieldGroup: 82722da7-1dd7-4f9e-9464-3763ba530b9c # Home Banner 3
handle: banner3Title
instructions: 'Title of Banner 3, 2 lines'
name: Banner-3-Title
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
