columnSuffix: null
contentColumnType: string
fieldGroup: 6ea547fb-7732-477d-a633-073ad70b7233 # Home Banner 1
handle: banner1Image
instructions: 'Top Banner Image'
name: Banner-1-Image
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0826ef63-13c2-4164-b44d-701e67a12144' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Update Background Image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0826ef63-13c2-4164-b44d-701e67a12144' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:0826ef63-13c2-4164-b44d-701e67a12144' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
