columnSuffix: null
contentColumnType: string
fieldGroup: 82722da7-1dd7-4f9e-9464-3763ba530b9c # Home Banner 3
handle: banner3Image
instructions: 'Image of banner 3'
name: Banner-3-Image
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0826ef63-13c2-4164-b44d-701e67a12144' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0826ef63-13c2-4164-b44d-701e67a12144' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:0826ef63-13c2-4164-b44d-701e67a12144' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
