columnSuffix: odbxsnns
contentColumnType: string
fieldGroup: 9732aa51-b630-40a6-96e6-bb26790edb8b # Footer
handle: footerEmail
instructions: 'footer section email address'
name: 'footer Email'
searchable: false
settings:
  placeholder: admin@horizonthemes.co.uk
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
