columnSuffix: gaizslbb
contentColumnType: string(255)
fieldGroup: 9732aa51-b630-40a6-96e6-bb26790edb8b # Footer
handle: instagram
instructions: ''
name: instagram
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
