columnSuffix: mlggyjzx
contentColumnType: text
fieldGroup: 7f2b0963-a4ad-4703-840c-08c8724c33b1 # home blue section
handle: mediaTitle
instructions: 'Two lines heading '
name: media-title
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
