columnSuffix: null
contentColumnType: string
fieldGroup: 7f2b0963-a4ad-4703-840c-08c8724c33b1 # home blue section
handle: mediaImage
instructions: 'left image of blue section'
name: 'media Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0826ef63-13c2-4164-b44d-701e67a12144' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0826ef63-13c2-4164-b44d-701e67a12144' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:0826ef63-13c2-4164-b44d-701e67a12144' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
