defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  9418c922-8791-4be4-80e6-15b330717c37: # Demo
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
